name: i18n-check

on:
    push:
        branches:
            - main
        paths:
            - 'src/i18n-keysets/**'
    workflow_dispatch:
    pull_request_target:
        types: ['opened', 'reopened', 'synchronize', 'closed']
        branches:
            - main
        paths:
            - 'src/i18n-keysets/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    i18n_check:
        if: github.actor != 'WeblateGravity'        
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Verifying changes with Weblate
              uses: dgaponov/weblate-action@v1.43.0
              with:
                  SERVER_URL: "https://weblate.gravity-ui.com"
                  TOKEN: ${{ secrets.WEBLATE_TOKEN }}
                  PROJECT: "datalens-fork"
                  MAIN_LANGUAGE: "ru"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
